package com.charmflex.cp.flexiexpensesmanager.features.transactions.di

import com.charmflex.cp.flexiexpensesmanager.features.transactions.ui.new_transaction.TransactionEditorViewModel
import com.charmflex.cp.flexiexpensesmanager.features.transactions.ui.new_transaction.TransactionEditorViewModelFactory
import com.charmflex.cp.flexiexpensesmanager.features.transactions.ui.transaction_detail.TransactionDetailViewModel
import com.charmflex.cp.flexiexpensesmanager.features.transactions.ui.transaction_detail.TransactionDetailViewModelFactory

internal interface TransactionInjector {
    val transactionEditorViewModelFactory: TransactionEditorViewModelFactory
    val transactionDetailViewModelFactory: TransactionDetailViewModelFactory
}